services:
  stille:
    build:
      context: ./ 
      args:
        - NODE_ENV=development
    command: npm run dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '5173:5173'
    volumes:
      - ./:/app
      - /app/node_modules